# Generated by Django 5.2 on 2026-08-28 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comppages', '0002_companypost'),
        ('posts', '0005_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='comppages.companypage'),
        ),
    ]
