# Generated by Django 5.2 on 2026-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_company_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_promoted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
