# Generated by Django 5.2 on 2026-04-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('startups', '0005_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='startups.companyprofile'),
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
