# Generated by Django 5.2 on 2026-04-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobpost_company_delete_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='hiring_status',
            field=models.CharField(choices=[('ACTIVELY_HIRING', 'Actively Hiring'), ('ACTIVELY_REVIEWING', 'Actively Reviewing')], default='ACTIVELY_HIRING', max_length=30),
        ),
    ]
