# Generated by Django 5.2 on 2026-05-03 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_skill_jobpost_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=255)),
                ('job_name', models.CharField(max_length=255)),
                ('resume_url', models.URLField(max_length=500)),
                ('applicant_id', models.CharField(db_index=True, max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Applied Job Log',
                'verbose_name_plural': 'Applied Job Logs',
                'ordering': ['-applied_at'],
            },
        ),
    ]
