# Generated by Django 5.2 on 2026-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_analysis',
            field=models.TextField(blank=True, help_text='Detailed AI analysis of the candidate fit'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_score',
            field=models.IntegerField(blank=True, help_text='AI generated fit score (0-100)', null=True),
        ),
    ]
