# Generated by Django 5.2 on 2026-05-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobapplication_ai_analysis_jobapplication_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='open_positions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
