# Generated by Django 5.2 on 2026-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobpost_department_jobpost_open_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
