# Generated by Django 5.2 on 2026-05-05 12:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobpost_is_ai_generated'),
        ('startups', '0009_companyhrprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPipeline',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Recruiter notes about the talent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_pipeline', to='startups.companyprofile')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_to_pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talent Pipeline Entry',
                'verbose_name_plural': 'Talent Pipeline Entries',
                'ordering': ['-added_at'],
                'unique_together': {('company', 'talent')},
            },
        ),
    ]
