# Generated by Django 5.2 on 2026-05-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_talentpipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentpipeline',
            name='status',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('CONTACTED', 'Contacted'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected')], default='LEAD', max_length=20),
        ),
    ]
