# Generated by Django 5.2 on 2026-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_talentpipeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentpipeline',
            name='status',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('CONTACTED', 'Contacted'), ('REPLIED', 'Replied'), ('PHONE_SCREEN', 'Phone Screen (Hiring Manager)'), ('FASE_FINAL', 'Fase Final'), ('OFFER_EXTENDED', 'Offer Extended'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected')], default='LEAD', max_length=20),
        ),
    ]
