# Generated by Django 5.2 on 2026-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_talentpipeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
