# Generated by Django 5.2 on 2026-05-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Permanent'), ('CONTRACT', 'Contractor'), ('INTERNSHIP', 'Internship')], max_length=20, null=True),
        ),
    ]
