# Generated by Django 5.2 on 2026-05-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_jobapplication_status'),
        ('startups', '0010_alter_companyhrprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='hr_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='startups.companyhrprofile'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_category',
            field=models.CharField(choices=[('IT', 'IT'), ('NON_IT', 'Non-IT')], default='IT', max_length=10),
        ),
    ]
