# Generated by Django 5.2 on 2026-05-11 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_startup_alter_designation_startup_and_more'),
        ('startups', '0009_companyhrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='startups.companyprofile'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='startups.startup'),
        ),
    ]
