# Generated by Django 5.2 on 2026-05-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_company_alter_organization_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
