# Generated by Django 5.2 on 2026-05-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
