# Generated by Django 5.2 on 2026-05-11 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('organization', '0002_alter_department_startup_alter_designation_startup_and_more'),
        ('startups', '0009_companyhrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='startups.startup'),
        ),
    ]
