# Generated by Django 5.2 on 2026-05-11 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_organization_alter_employee_startup'),
        ('jobs', '0013_jobapplication_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_employee', to='jobs.jobapplication'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
