# Generated by Django 5.2 on 2026-05-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_job_application_alter_employee_avatar'),
        ('organization', '0004_organization_banner_url_organization_company_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAadhaarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('enrollment_no', models.CharField(blank=True, max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_detail', to='employees.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_details', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Employee Aadhaar Detail',
                'verbose_name_plural': 'Employee Aadhaar Details',
            },
        ),
        migrations.CreateModel(
            name='EmployeeJoiningDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('probation_period', models.CharField(blank=True, default='3 Months', max_length=50)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joining_detail', to='employees.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joining_details', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Employee Joining Detail',
                'verbose_name_plural': 'Employee Joining Details',
            },
        ),
        migrations.CreateModel(
            name='EmployeePANDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pan_detail', to='employees.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pan_details', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Employee PAN Detail',
                'verbose_name_plural': 'Employee PAN Details',
            },
        ),
    ]
