# Generated by Django 5.2 on 2026-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeebankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='portal_username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True),
        ),
    ]
