# Generated by Django 5.2 on 2026-05-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_portal_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='portal_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
