# Generated by Django 5.2

import uuid
from django.db import migrations, models
import django.db.models.deletion


def populate_employee_users_and_cleanup_shadow_users(apps, schema_editor):
    """
    1. Populates EmployeeUser records for all existing employees.
    2. Safely unlinks and cleans up shadow CustomUser records created under @employee.b2linq.local or emp_*.
    """
    Employee = apps.get_model('employees', 'Employee')
    EmployeeUser = apps.get_model('employees', 'EmployeeUser')
    from django.contrib.auth.hashers import make_password

    try:
        CustomUser = apps.get_model('useraccounts', 'CustomUser')
    except LookupError:
        CustomUser = None

    for emp in Employee.objects.all():
        portal_username = emp.portal_username
        if not portal_username:
            first_name = (emp.first_name or 'emp').lower().replace(' ', '')
            base_uname = f"emp_{first_name}"
            unique_uname = base_uname
            c = 1
            while Employee.objects.filter(portal_username=unique_uname).exists():
                unique_uname = f"{base_uname}{c}"
                c += 1
            portal_username = unique_uname
            emp.portal_username = portal_username
            emp.save(update_fields=['portal_username'])

        raw_pw = emp.portal_password or 'B2lq_Welcome123'
        hashed_pw = make_password(raw_pw)

        emp_user = EmployeeUser.objects.filter(employee=emp).first()
        if not emp_user:
            role = getattr(emp, 'role', 'EMPLOYEE') or 'EMPLOYEE'
            status_val = getattr(emp, 'status', 'ACTIVE')
            EmployeeUser.objects.create(
                employee=emp,
                portal_username=portal_username,
                email=emp.email,
                password=hashed_pw,
                role=role,
                is_active=(status_val not in ['EXITED', 'INACTIVE']),
            )
        else:
            if not emp_user.password:
                emp_user.password = hashed_pw
                emp_user.save(update_fields=['password'])

        # Clean up shadow CustomUser if linked
        if emp.user_id and CustomUser:
            try:
                shadow_user = CustomUser.objects.filter(id=emp.user_id).first()
                if shadow_user:
                    is_shadow = (
                        shadow_user.email.endswith('@employee.b2linq.local') or
                        shadow_user.email.startswith('emp_') or
                        (shadow_user.role == 'OPERATIONS' and shadow_user.email == emp.email)
                    )
                    if is_shadow:
                        emp.user = None
                        emp.save(update_fields=['user'])
                        shadow_user.delete()
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager')], db_index=True, default='EMPLOYEE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_user', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee User',
                'verbose_name_plural': 'Employee Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(populate_employee_users_and_cleanup_shadow_users, reverse_code=migrations.RunPython.noop),
    ]
