# Generated by Django 5.2 on 2026-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_comment_deleted_at_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=10),
        ),
    ]
