# Generated by Django 5.2 on 2026-04-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_mentorprofile_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
