# Generated by Django 5.2 on 2026-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_alter_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='List of educational qualifications including CGPA'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='experience',
            field=models.JSONField(blank=True, default=list, help_text='List of work experiences'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='resume_url',
            field=models.URLField(blank=True, help_text="Link to the user's resume PDF", max_length=500),
        ),
    ]
