# Generated by Django 5.2 on 2026-05-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['display_order', 'price'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Example: Most Popular', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_ai_hiring_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_ai_interview_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_ai_resume_screening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_analytics_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_autonomous_ai_agents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_candidate_evaluation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_custom_workflows',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_dedicated_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_email_automation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_employee_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_hiring_workflow_automation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_hr_toolkit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_interview_scheduling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_offer_letter_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_predictive_ai_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_role_based_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_task_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_team_collaboration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_third_party_integrations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_user_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='short_tagline',
            field=models.CharField(blank=True, help_text='Example: Complete AI Hiring Suite', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='agent_intelligence_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='analytics_governance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='employee_limit',
            field=models.CharField(help_text='Example: 1-10 Employees', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='employee_self_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of feature highlights'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='hiring_ats_automation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='onboarding_workflow',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='system_integrations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('trial', 'Trial')], default='active', max_length=20),
        ),
    ]
