# Generated by Django 5.2 on 2026-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_manualpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='screenshot',
            field=models.URLField(blank=True, help_text='ImageKit CDN URL for transaction screenshot', max_length=500, null=True),
        ),
    ]
