# Generated by Django 5.2 on 2026-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_manualpayment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='payment_type',
            field=models.CharField(choices=[('new', 'New Subscription'), ('upgrade', 'Upgrading Subscription')], default='new', help_text='Whether this is a new subscription or an upgrade', max_length=20),
        ),
        migrations.AddField(
            model_name='manualpayment',
            name='upgrade_upi_or_phone',
            field=models.CharField(blank=True, help_text="PhonePe Number or UPI ID (required only when payment_type is 'upgrade')", max_length=255, null=True),
        ),
    ]
