# Generated by Django 5.2 on 2026-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_manualpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpayment',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name of the sender/payer (e.g. HDFC Bank, ICICI Bank)', max_length=150, null=True),
        ),
    ]
