# Generated by Django 5.2 on 2026-05-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Sales Inquiries',
            },
        ),
    ]
