# Generated by Django 5.2 on 2026-05-16 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AIrounds', '0014_interviewround_round_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('integrity_score', models.IntegerField(default=100, help_text='Starting score is 100, drops with violations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring', to='AIrounds.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch Detected'), ('FULLSCREEN_EXIT', 'Exited Fullscreen'), ('FACE_MISSING', 'Candidate Face Not Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('PHONE_DETECTED', 'Mobile Phone Detected'), ('HEAD_AWAY', 'Looking Away From Screen'), ('UNAUTHORIZED_DEVICE', 'External Device Plugged In'), ('CLIPBOARD_ACCESS', 'Copy/Paste Attempted')], max_length=50)),
                ('severity', models.CharField(default='MEDIUM', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('screenshot_url', models.URLField(blank=True, max_length=500, null=True)),
                ('proctoring_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='Aisecurity.proctoringsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
