# Generated by Django 5.2 on 2026-05-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aisecurity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationlog',
            name='violation_type',
            field=models.CharField(choices=[('TAB_SWITCH', 'Tab Switch Detected'), ('FULLSCREEN_EXIT', 'Exited Fullscreen'), ('FACE_MISSING', 'Candidate Face Not Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('PHONE_DETECTED', 'Mobile Phone Detected'), ('HEAD_AWAY', 'Looking Away From Screen'), ('UNAUTHORIZED_DEVICE', 'External Device Plugged In'), ('CLIPBOARD_ACCESS', 'Copy/Paste Attempted'), ('SPLIT_SCREEN_DETECTED', 'Split Screen Mode Active'), ('EXTERNAL_TOOL_USAGE', 'Interaction with External Tool'), ('SCREENSHOT_ATTEMPT', 'Screenshot or DevTools Attempt')], max_length=50),
        ),
    ]
