# Generated by Django 5.2 on 2026-05-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aisecurity', '0002_alter_violationlog_violation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationlog',
            name='duration_seconds',
            field=models.FloatField(default=0.0),
        ),
    ]
