# Generated by Django 5.2 on 2026-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='category',
            field=models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('OCCASIONAL', 'Occasional Leave'), ('NATIONAL', 'National Holiday / Leave'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
