# Generated by Django 5.2 on 2026-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_leavetype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
