# Generated by Django 5.2 on 2026-05-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_leavetype_date_alter_leavetype_max_days_per_year'),
        ('organization', '0004_organization_banner_url_organization_company_size_and_more'),
        ('startups', '0009_companyhrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='startups.companyprofile'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='startups.companyprofile'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='startups.startup'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='startups.startup'),
        ),
    ]
