# Generated by Django 5.2 on 2026-04-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatroom_is_deleted_remove_message_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
