# Generated by Django 5.2 on 2026-04-28 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatroom_status_remove_message_status_and_more'),
        ('interactions', '0007_alter_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='interactions.connection'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
