# Generated by Django 5.2 on 2026-05-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_connection_chatroom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('connection', 'Connection Chat'), ('direct', 'Direct / HR Chat')], db_index=True, default='connection', help_text="'connection' for network chats, 'direct' for HR/recruiter chats", max_length=20),
        ),
    ]
