# Generated by Django 5.2 on 2026-04-19 02:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('pitch', models.TextField()),
                ('industry', models.CharField(db_index=True, max_length=150)),
                ('stage', models.CharField(help_text='e.g. Concept, MVP, Seed, Series A', max_length=100)),
                ('seeking_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('website_url', models.URLField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
                'ordering': ['-created_at'],
            },
        ),
    ]
