# Generated by Django 5.2 on 2026-04-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_remove_startup_is_deleted_startup_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='status',
        ),
        migrations.AddField(
            model_name='startup',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
