# Generated by Django 5.2 on 2026-04-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
