# Generated by Django 5.2 on 2026-04-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_companyprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_genuine',
            field=models.BooleanField(default=False),
        ),
    ]
