# Generated by Django 5.2 on 2026-04-27 08:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0008_companyprofile_company_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHRProfile',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('profile_image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to='startups.companyprofile')),
            ],
            options={
                'verbose_name': 'Company HR Profile',
                'verbose_name_plural': 'Company HR Profiles',
            },
        ),
    ]
