# Generated by Django 5.2 on 2026-05-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0009_companyhrprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhrprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profiles', to='startups.companyprofile'),
        ),
    ]
