# Generated by Django 5.2 on 2026-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0010_alter_companyhrprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
