# Generated by Django 5.2 on 2026-05-26 04:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
        ('startups', '0010_alter_companyhrprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceScoreBreakdown',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avg_goal_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_feedback_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('final_calculated_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_breakdown', to='performance.performancereview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceWeightConfiguration',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_weight', models.DecimalField(decimal_places=2, default=0.6, help_text='Weight for goal progress percentage (e.g., 0.60 for 60%)', max_digits=3)),
                ('feedback_weight', models.DecimalField(decimal_places=2, default=0.4, help_text='Weight for 360/manager feedback ratings (e.g., 0.40 for 40%)', max_digits=3)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_weight_config', to='startups.startup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
