# Generated by Django 5.2 on 2026-05-26 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_performancescorebreakdown_and_more'),
        ('startups', '0010_alter_companyhrprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefeedback',
            name='feedback_type',
            field=models.CharField(choices=[('self', 'Self Appraisal'), ('peer', 'Peer Review'), ('manager', 'Manager Review'), ('direct_report', 'Direct Report')], default='peer', max_length=20),
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_goals', to='performance.goal'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SELF_APPRAISAL', 'Self-Appraisal Pending'), ('MANAGER_REVIEW', 'Manager Review Pending'), ('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('core', 'Core'), ('technical', 'Technical'), ('leadership', 'Leadership')], default='core', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='startups.startup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetencyScore',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, help_text='1-5 rating scale', null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of total competency score', max_digits=4)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.competency')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='performance.performancereview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_cycles', to='startups.startup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='performancereview',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='performance.performancecycle'),
        ),
    ]
