# Generated by Django 5.2 on 2026-05-26 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_banner_url_organization_company_size_and_more'),
        ('performance', '0003_employeefeedback_feedback_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='performancecycle',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='performanceweightconfiguration',
            name='startup',
        ),
        migrations.AddField(
            model_name='competency',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='goal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='performancecycle',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_cycles', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='performanceweightconfiguration',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_weight_config', to='organization.organization'),
        ),
    ]
