# Generated by Django 5.2 on 2026-05-30 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_banner_url_organization_company_size_and_more'),
        ('performance', '0004_remove_competency_startup_remove_goal_startup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAIInsight',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insights', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
