# Generated by Django 5.2 on 2026-04-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='headline',
            field=models.CharField(blank=True, help_text='Short professional headline', max_length=255),
        ),
        migrations.AddField(
            model_name='founder',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='founder',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
