# Generated by Django 5.2 on 2026-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founders', '0003_founder_deleted_at_founder_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='founder',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=10),
        ),
    ]
