# Generated by Django 5.2 on 2026-04-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founders', '0004_remove_founder_is_deleted_founder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='status',
        ),
        migrations.AddField(
            model_name='founder',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
