# Generated by Django 5.2 on 2026-04-19 02:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('preferred_stages', models.JSONField(blank=True, default=list, help_text='e.g. Pre-seed, Seed, Series A')),
                ('preferred_industries', models.JSONField(blank=True, default=list, help_text='e.g. AI, FinTech, HealthTech')),
                ('minimum_investment_range', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('maximum_investment_range', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('linkedin_url', models.URLField(blank=True, max_length=255)),
                ('portfolio_url', models.URLField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
            },
        ),
    ]
