# Generated by Django 5.2 on 2026-04-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_remove_investor_is_deleted_investor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='status',
        ),
        migrations.AddField(
            model_name='investor',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
