# Generated by Django 5.2 on 2026-04-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_remove_investor_status_investor_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='banner_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
