# Generated by Django 5.2 on 2026-06-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='action_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='candidate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='interview_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
