# Generated by Django 5.2 on 2026-06-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditsystem', '0002_credittransaction_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Negative for consumption, positive for replenishment/allocation.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
