# Generated by Django 5.2 on 2026-08-15 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditsystem', '0003_alter_credittransaction_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCreditVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits_requested', models.DecimalField(decimal_places=2, help_text='Number of AI credits requested', max_digits=10)),
                ('package_name', models.CharField(default='Credit Top-up', max_length=150)),
                ('amount_paid', models.CharField(blank=True, help_text='Amount paid e.g. ₹499', max_length=50, null=True)),
                ('transaction_id', models.CharField(help_text='UPI Ref No / Transaction Reference ID', max_length=255)),
                ('payment_method', models.CharField(default='UPI / GPay / PhonePe', max_length=100)),
                ('upi_or_phone', models.CharField(blank=True, help_text='Sender UPI ID or Phone number', max_length=255, null=True)),
                ('screenshot', models.TextField(blank=True, help_text='URL or Base64 data of payment screenshot', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes or rejection reasons', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_credit_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Credit Verification',
                'verbose_name_plural': 'Manual Credit Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
