# Generated by Django 5.2 on 2026-05-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_organization_banner_url_organization_company_size_and_more'),
        ('startups', '0010_alter_companyhrprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('recurrence', models.CharField(default='daily', max_length=50)),
                ('execution_time', models.TimeField(default='09:00:00')),
                ('task_type', models.CharField(default='payroll_runs', max_length=100)),
                ('notification_email', models.EmailField(blank=True, default='', max_length=254)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
        ),
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_model', models.CharField(default='gemini-2.5-flash', max_length=100)),
                ('temperature', models.FloatField(default=0.1)),
                ('max_iterations', models.IntegerField(default=30)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('autonomy_level', models.CharField(default='full_autonomy', max_length=50)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startups.startup')),
            ],
        ),
    ]
