# Generated by Django 5.2 on 2026-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentscheduling',
            name='day_of_month',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='agentscheduling',
            name='day_of_week',
            field=models.CharField(blank=True, default='Monday', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agentscheduling',
            name='month_of_year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
