# Generated by Django 5.2 on 2026-05-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsettings', '0002_agentscheduling_day_of_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentscheduling',
            name='task_type',
            field=models.CharField(default='payroll_runs', max_length=500),
        ),
    ]
