# Generated by Django 5.2 on 2026-06-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentsettings', '0003_alter_agentscheduling_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsettings',
            name='temperature',
        ),
    ]
