# Generated by Django 5.2 on 2026-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsettings', '0004_remove_agentsettings_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentscheduling',
            name='command',
            field=models.TextField(blank=True, default='Execute default task audit and sync pipeline'),
        ),
        migrations.AddField(
            model_name='agentscheduling',
            name='max_executions',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='agentscheduling',
            name='run_count',
            field=models.IntegerField(default=0),
        ),
    ]
