# Generated by Django 5.2 on 2026-06-01 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsettings', '0005_agentscheduling_command_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSchedulingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(default='payroll_runs', max_length=200)),
                ('command', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='running', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(default=0.0)),
                ('actions_performed', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agentsettings.agentscheduling')),
            ],
        ),
    ]
