# Generated by Django 5.2 on 2026-08-28 05:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0011_companyprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPage',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('page_type', models.CharField(choices=[('COMPANY', 'Company / Enterprise'), ('SMALL_BUSINESS', 'Small Business (<200 employees)'), ('STARTUP', 'Startup'), ('EDUCATIONAL', 'Educational Institution'), ('NON_PROFIT', 'Non-Profit Organization')], default='COMPANY', max_length=50)),
                ('overview', models.TextField(blank=True)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('custom_banner_url', models.URLField(blank=True, max_length=500)),
                ('custom_logo_url', models.URLField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('call_to_action_label', models.CharField(default='Visit website', max_length=50)),
                ('call_to_action_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_details', to='startups.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Page',
                'verbose_name_plural': 'Company Pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
