# Generated by Django 5.2 on 2026-08-28 06:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comppages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPost',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_page_posts', to=settings.AUTH_USER_MODEL)),
                ('company_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_posts', to='comppages.companypage')),
            ],
            options={
                'verbose_name': 'Company Post',
                'verbose_name_plural': 'Company Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
