# Generated by Django 5.2 on 2026-08-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comppages', '0002_companypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypost',
            name='is_promoted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
