# Generated by Django 5.2 on 2026-05-08 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('startups', '0009_companyhrprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='startups.startup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='startups.startup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.allowance')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='startups.startup')),
            ],
            options={
                'unique_together': {('startup', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_allowances', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payroll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowances', models.ManyToManyField(through='payroll.EmployeeAllowance', to='payroll.allowance')),
                ('deductions', models.ManyToManyField(through='payroll.EmployeeDeduction', to='payroll.deduction')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employeededuction',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarystructure'),
        ),
        migrations.AddField(
            model_name='employeeallowance',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarystructure'),
        ),
    ]
