# Generated by Django 5.2 on 2026-05-20 08:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_portal_username'),
        ('payroll', '0001_initial'),
        ('startups', '0009_companyhrprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='esi_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Employee State Insurance percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='House Rent Allowance', max_digits=15),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime rate per hour', max_digits=10),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Provident Fund percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default tax deduction percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='employees.employee')),
                ('payroll_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payroll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pf_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reimbursement_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='employees.employee')),
                ('payroll_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payroll')),
            ],
            options={
                'unique_together': {('employee', 'payroll_cycle')},
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrecord'),
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel & Commute'), ('MEALS', 'Meals & Entertainment'), ('EQUIPMENT', 'Office Equipment & Gadgets'), ('UTILITIES', 'Internet & Utilities'), ('OTHER', 'Other Expenses')], default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='reimbursement_proofs/')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slab_name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Tax percentage', max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Minimum income threshold', max_digits=15)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum income threshold', max_digits=15, null=True)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_configs', to='startups.startup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
