# Generated by Django 5.2 on 2026-05-20 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll_approved_by_payslip_generated_at_and_more'),
        ('startups', '0009_companyhrprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='INR', help_text='e.g. INR, USD, EUR', max_length=10)),
                ('automation_enabled', models.BooleanField(default=True)),
                ('pf_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('esi_percentage', models.DecimalField(decimal_places=2, default=1.75, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_setting', to='startups.startup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
