# Generated by Django 5.2 on 2026-05-20 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollsetting'),
        ('startups', '0009_companyhrprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PAYROLL', 'Payroll Related'), ('OFFER_LETTER', 'Offer Letter'), ('JOINING_LETTER', 'Joining Letter')], default='PAYROLL', max_length=50)),
                ('content', models.TextField(blank=True, help_text='Template body content in rich-text, HTML or markdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='startups.startup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
