# Generated by Django 5.2 on 2026-05-31 11:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_documenttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeallowance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='employeededuction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='esi_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Employee State Insurance percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='House Rent Allowance', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Overtime rate per hour', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='pf_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Provident Fund percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default tax deduction percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum income threshold', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, help_text='Minimum income threshold', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Tax percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
