# Generated by Django 5.2 on 2026-06-01 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_employeeallowance_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='director_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='director_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='director_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_approved_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='finance_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='finance_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='finance_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approved_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_approved_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='director_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='finance_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='finance_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approved_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
