# Generated by Django 5.2 on 2026-08-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payroll_director_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='payslips/'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='proof',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='reimbursement_proofs/'),
        ),
    ]
