# Generated by Django 5.2 on 2026-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_payslip_pdf_file_alter_reimbursement_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
