# Generated by Django 5.2 on 2026-08-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payrollsetting_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='enable_leave_deductions',
            field=models.BooleanField(default=True, help_text='Enable automatic absence and unpaid leave penalty deductions globally'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='deduct_absent_leaves',
            field=models.BooleanField(default=True, help_text='Calculate and deduct absent/unpaid leave penalty from monthly pay'),
        ),
    ]
