# Generated by Django 5.2 on 2026-08-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payrollsetting_enable_leave_deductions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='enable_statutory_deductions',
            field=models.BooleanField(default=True, help_text='Enable statutory PF and ESI deductions in payroll calculations'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='enable_tax_deductions',
            field=models.BooleanField(default=True, help_text='Enable automatic tax deductions in payroll calculations'),
        ),
    ]
