# Generated by Django 5.2 on 2026-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_customuser_deleted_at_customuser_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=10),
        ),
    ]
