# Generated by Django 5.2 on 2026-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_remove_customuser_is_deleted_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_top_voice',
            field=models.BooleanField(default=False),
        ),
    ]
