# Generated by Django 5.2 on 2026-04-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0005_customuser_is_premium_customuser_is_top_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_creator_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_hiring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_open_to_work',
            field=models.BooleanField(default=False),
        ),
    ]
