# Generated by Django 5.2 on 2026-04-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_customuser_is_creator_mode_customuser_is_hiring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FOUNDER', 'Founder'), ('INVESTOR', 'Investor'), ('MENTOR', 'Mentor')], db_index=True, default='FOUNDER', max_length=20),
        ),
    ]
