# Generated by Django 5.2 on 2026-05-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0010_wsticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FOUNDER', 'Founder'), ('CO_FOUNDER', 'Co-Founder'), ('INVESTOR', 'Investor'), ('MENTOR', 'Mentor'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('ENGINEER', 'Engineer'), ('PRODUCT', 'Product Manager'), ('DESIGN', 'Designer'), ('OPERATIONS', 'Operations')], db_index=True, default='FOUNDER', max_length=20),
        ),
    ]
