# Generated by Django 5.2 on 2026-06-02 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahrmagent1', '0002_agentchathistory'),
        ('organization', '0004_organization_banner_url_organization_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentexecution',
            name='execution_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agentlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agentlog',
            name='log_level',
            field=models.CharField(default='INFO', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('action_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_actions', to='Ahrmagent1.agentexecution')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkpoint_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='Ahrmagent1.agentexecution')),
            ],
        ),
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(max_length=100)),
                ('decision_data', models.JSONField(default=dict)),
                ('reasoning_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='Ahrmagent1.agentexecution')),
            ],
        ),
        migrations.CreateModel(
            name='AgentGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.TextField()),
                ('goal_type', models.CharField(default='autonomous', max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='Ahrmagent1.agentgoal'),
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(max_length=50)),
                ('memory_key', models.CharField(max_length=255)),
                ('memory_value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='Ahrmagent1.agentexecution')),
            ],
        ),
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(max_length=50)),
                ('schedule_expression', models.CharField(max_length=100)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Ahrmagent1.agentgoal')),
            ],
        ),
    ]
