# Generated by Django 5.2 on 2026-06-02 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahrmagent1', '0003_agentexecution_execution_version_agentlog_created_at_and_more'),
        ('organization', '0004_organization_banner_url_organization_company_size_and_more'),
        ('startups', '0010_alter_companyhrprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentexecution',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_executions', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_executions', to='startups.startup'),
        ),
    ]
