# Generated by Django 5.2 on 2026-06-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahrmagent1', '0004_agentexecution_organization_agentexecution_startup'),
        ('organization', '0004_organization_banner_url_organization_company_size_and_more'),
        ('startups', '0010_alter_companyhrprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentgoal',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_goals', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='agentschedule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_schedules', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='agentschedule',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_schedules', to='startups.startup'),
        ),
        migrations.AlterField(
            model_name='agentgoal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_goals', to='organization.organization'),
        ),
    ]
