# Generated by Django 5.2 on 2026-06-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahrmagent1', '0005_agentgoal_startup_agentschedule_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentchathistory',
            name='conversation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
