# Generated by Django 5.2 on 2026-05-05 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScreeningReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(db_index=True)),
                ('job_title', models.CharField(max_length=255)),
                ('results', models.JSONField(help_text='Detailed screening results including candidate scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_screening_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Screening Report',
                'verbose_name_plural': 'AI Screening Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
