# Generated by Django 5.2 on 2026-05-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscreeningreport',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
