# Generated by Django 5.2 on 2026-05-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIAgents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisearchhistory',
            name='candidates_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
