# Generated by Django 5.2 on 2026-05-23 11:00

from django.db import migrations

def update_seo_data(apps, schema_editor):
    Page = apps.get_model('seo', 'Page')
    PageSEO = apps.get_model('seo', 'PageSEO')
    
    seo_data = [
        {
            'url_path': '/',
            'name': 'Home Page',
            'meta_title': 'B2linq Platform | Autonomous Hiring Orchestration',
            'meta_description': 'Deploy specialized AI agents that autonomously source talent, screen capabilities, conduct structured voice interviews, and deliver precise hiring verdicts in minutes—from sourcing to handshake.',
            'meta_keywords': 'autonomous hiring, recruiter AI agent, AI talent acquisition, resume parsing, voice screening interviews, HR automation, hiring handshake',
            'og_title': 'B2linq Platform | Autonomous Hiring Orchestration',
            'og_description': 'Deploy specialized AI agents that autonomously source talent, screen capabilities, conduct structured voice interviews, and deliver precise hiring verdicts in minutes—from sourcing to handshake.',
        },
        {
            'url_path': '/aboutus',
            'name': 'About Us Page',
            'meta_title': 'About Us | B2linq Autonomous Hiring Platform',
            'meta_description': 'Learn about our mission to eliminate manual recruiting bottlenecks and build the leading autonomous agentic infrastructure connecting exceptional talent and teams.',
            'meta_keywords': 'about b2linq, recruitment infrastructure, autonomous hiring, hiring workflow automation',
            'og_title': 'About Us | B2linq Autonomous Hiring Platform',
            'og_description': 'Learn about our mission to eliminate manual recruiting bottlenecks and build the leading autonomous agentic infrastructure connecting exceptional talent and teams.',
        },
        {
            'url_path': '/blogs',
            'name': 'Blogs List Page',
            'meta_title': 'Recruitment & AI Sourcing Insights | B2linq Blog',
            'meta_description': 'Read the latest insights, guides, and news from the B2linq team on autonomous hiring pipelines, conversational AI screening, and HR automation.',
            'meta_keywords': 'recruitment blog, AI hiring trends, talent sourcing guide, voice screening, HR tech insights',
            'og_title': 'Recruitment & AI Sourcing Insights | B2linq Blog',
            'og_description': 'Read the latest insights, guides, and news from the B2linq team on autonomous hiring pipelines, conversational AI screening, and HR automation.',
        },
        {
            'url_path': '/book-demo',
            'name': 'Book Demo Page',
            'meta_title': 'Book a Demo | B2linq Autonomous Hiring Orchestration',
            'meta_description': 'Schedule a live custom demonstration of our autonomous hiring flow. Observe specialized AI agents sourcing, screening, and interviewing candidates in real-time.',
            'meta_keywords': 'book custom demo, live hiring flow, AI screening demo, HR automation demo',
            'og_title': 'Book a Demo | B2linq Autonomous Hiring Orchestration',
            'og_description': 'Schedule a live custom demonstration of our autonomous hiring flow. Observe specialized AI agents sourcing, screening, and interviewing candidates in real-time.',
        },
        {
            'url_path': '/careers',
            'name': 'Careers Page',
            'meta_title': 'Join the Pioneers of Autonomous Hiring | B2linq Careers',
            'meta_description': 'Help us build the next generation of recruitment infrastructure. Explore open roles and shape the future of autonomous agentic work.',
            'meta_keywords': 'careers at b2linq, tech job openings, hiring platform developer, software careers',
            'og_title': 'Join the Pioneers of Autonomous Hiring | B2linq Careers',
            'og_description': 'Help us build the next generation of recruitment infrastructure. Explore open roles and shape the future of autonomous agentic work.',
        },
        {
            'url_path': '/pricing',
            'name': 'Pricing Page',
            'meta_title': 'Pricing Plans | B2linq Autonomous Recruitment Platform',
            'meta_description': 'Simple, transparent pricing tailored to your scale. Deploy autonomous AI sourcing, screening, and voice interview agents that save hours of human effort.',
            'meta_keywords': 'recruiter subscription, pricing plans, hiring software cost, AI hiring platform price',
            'og_title': 'Pricing Plans | B2linq Autonomous Recruitment Platform',
            'og_description': 'Simple, transparent pricing tailored to your scale. Deploy autonomous AI sourcing, screening, and voice interview agents that save hours of human effort.',
        }
    ]
    
    for item in seo_data:
        page, created = Page.objects.get_or_create(url_path=item['url_path'], defaults={'name': item['name']})
        if not created and page.name != item['name']:
            page.name = item['name']
            page.save()
            
        PageSEO.objects.update_or_create(
            page=page,
            defaults={
                'meta_title': item['meta_title'],
                'meta_description': item['meta_description'],
                'meta_keywords': item['meta_keywords'],
                'og_title': item['og_title'],
                'og_description': item['og_description'],
                'og_type': 'website'
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_seo_data),
    ]
