# Generated by Django 5.2 on 2026-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_update_seo_to_hiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageseo',
            name='is_nofollow',
            field=models.BooleanField(default=False, help_text='Instruct search engines not to follow links on this page'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='is_noindex',
            field=models.BooleanField(default=False, help_text='Instruct search engines not to index this page'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='page_type',
            field=models.CharField(choices=[('HOME', 'Home Page'), ('ABOUT', 'About Us Page'), ('PRICING', 'Pricing Page'), ('BLOG', 'Blogs List Page'), ('ARTICLE', 'Blog Article'), ('CAREERS', 'Careers Page'), ('CONTACT', 'Contact/Demo Page')], default='HOME', max_length=20),
        ),
    ]
