# Generated by Django 5.2 on 2026-05-07 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='max_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='timer_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='invite_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='verification_status',
            field=models.JSONField(default=dict),
        ),
    ]
