# Generated by Django 5.2 on 2026-05-07 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0002_interviewround_max_questions_interviewround_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
