# Generated by Django 5.2 on 2026-05-07 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0003_alter_interviewsession_invite_token'),
        ('jobs', '0011_alter_talentpipeline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='jobs.jobapplication'),
        ),
    ]
