# Generated by Django 5.2 on 2026-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0004_interviewsession_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('CODE', 'Code')], default='TEXT', max_length=10),
        ),
    ]
