# Generated by Django 5.2 on 2026-05-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0005_interviewquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewround',
            name='round_type',
            field=models.CharField(choices=[('APPLICATION_SCREENING', 'Application Screening'), ('ATS_RESUME_SCREENING', 'ATS Resume Screening'), ('HR_SCREENING', 'HR Screening'), ('APTITUDE_ROUND', 'Aptitude Round'), ('LOGICAL_REASONING', 'Logical Reasoning Round'), ('COMMUNICATION_ROUND', 'Communication Round'), ('TECHNICAL_SCREENING', 'Technical Screening'), ('TECHNICAL_INTERVIEW', 'Technical Interview'), ('CODING_ROUND', 'Coding Round'), ('LIVE_CODING', 'Live Coding Round'), ('MACHINE_CODING', 'Machine Coding Round'), ('DEBUGGING_ROUND', 'Debugging Round'), ('DATABASE_ROUND', 'Database Round'), ('API_DESIGN', 'API Design Round'), ('BACKEND_ROUND', 'Backend Round'), ('FRONTEND_ROUND', 'Frontend Round'), ('FULL_STACK_ROUND', 'Full Stack Round'), ('DEVOPS_ROUND', 'DevOps Round'), ('CLOUD_ROUND', 'Cloud Round'), ('SECURITY_ROUND', 'Security Round'), ('AI_ML_ROUND', 'AI/ML Round'), ('SYSTEM_DESIGN', 'System Design Round'), ('ARCHITECTURE_ROUND', 'Architecture Round'), ('CASE_STUDY', 'Case Study Round'), ('PRODUCT_THINKING', 'Product Thinking Round'), ('BEHAVIORAL_ROUND', 'Behavioral Round'), ('SITUATIONAL_ROUND', 'Situational Round'), ('LEADERSHIP_ROUND', 'Leadership Round'), ('TEAM_COLLABORATION', 'Team Collaboration Round'), ('MANAGERIAL_ROUND', 'Managerial Round'), ('CULTURAL_FIT', 'Cultural Fit Round'), ('CLIENT_ROUND', 'Client Round'), ('DIRECTOR_ROUND', 'Director Round'), ('CTO_ROUND', 'CTO Round'), ('FOUNDER_ROUND', 'Founder Round'), ('FINAL_HR_ROUND', 'Final HR Round'), ('SALARY_NEGOTIATION', 'Salary Negotiation Round'), ('OFFER_DISCUSSION', 'Offer Discussion Round'), ('BGV_ROUND', 'Background Verification Round'), ('PRE_ONBOARDING', 'Pre-Onboarding Round')], max_length=50),
        ),
    ]
