# Generated by Django 5.2 on 2026-05-08 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0007_interviewround_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='mcq_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('', 'None (Not Applicable)'), ('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('TYPESCRIPT', 'TypeScript'), ('JAVA', 'Java'), ('CSHARP', 'C#'), ('CPP', 'C++'), ('C', 'C'), ('GO', 'Go'), ('RUST', 'Rust'), ('RUBY', 'Ruby'), ('PHP', 'PHP'), ('SWIFT', 'Swift'), ('KOTLIN', 'Kotlin'), ('DART', 'Dart'), ('R', 'R'), ('SQL', 'SQL'), ('SHELL', 'Shell / Bash')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='question_format',
            field=models.CharField(choices=[('TEXT', 'Text / Typing Answer'), ('MCQ', 'Multiple Choice (Single Answer)'), ('MULTI_SELECT', 'Multiple Choice (Multiple Answers)'), ('CODE', 'Code / Programming')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text / Typing'), ('MCQ', 'Multiple Choice (Single)'), ('MULTI_SELECT', 'Multiple Select'), ('CODE', 'Code / Programming')], default='TEXT', max_length=20),
        ),
        migrations.CreateModel(
            name='CandidateInterviewLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_link', to='AIrounds.interviewsession')),
            ],
        ),
    ]
