# Generated by Django 5.2 on 2026-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0008_interviewquestion_mcq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinterviewlink',
            name='exam_password',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidateinterviewlink',
            name='exam_username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, unique=True),
        ),
    ]
