# Generated by Django 5.2 on 2026-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0009_candidateinterviewlink_exam_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
