# Generated by Django 5.2 on 2026-05-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0010_interviewquestion_marks_interviewround_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='ideal_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
