# Generated by Django 5.2 on 2026-05-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0011_interviewquestion_ideal_answer'),
        ('jobs', '0013_jobapplication_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='jobs.jobapplication'),
        ),
    ]
