# Generated by Django 5.2 on 2026-05-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0012_alter_interviewsession_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewround',
            name='difficulty',
            field=models.CharField(choices=[('AUTO', 'AI Recommended'), ('ENTRY', 'Entry Level'), ('MID', 'Mid Level'), ('SENIOR', 'Senior Level'), ('LEAD', 'Lead Level')], default='MID', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewround',
            name='question_format',
            field=models.CharField(choices=[('AUTO', 'AI Recommended'), ('TEXT', 'Text / Typing Answer'), ('MCQ', 'Multiple Choice (Single Answer)'), ('MULTI_SELECT', 'Multiple Choice (Multiple Answers)'), ('CODE', 'Code / Programming')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewround',
            name='strategy_tier',
            field=models.CharField(choices=[('AUTO', 'AI Auto-select'), ('TECHNICAL', 'Technical Screen'), ('CODING', 'Live Code Assessment'), ('HR', 'Cultural Alignment'), ('SYSTEM_DESIGN', 'Architecture Design'), ('BEHAVIORAL', 'Situational Analysis')], default='TECHNICAL', max_length=50),
        ),
    ]
