# Generated by Django 5.2 on 2026-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0013_alter_interviewround_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='round_category',
            field=models.CharField(choices=[('NON_CODING', 'Non-Coding'), ('CODING', 'Coding')], default='NON_CODING', max_length=20),
        ),
    ]
