# Generated by Django 5.2 on 2026-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0015_alter_interviewsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Text / Typing'), ('MCQ', 'Multiple Choice (Single)'), ('MULTI_SELECT', 'Multiple Select'), ('CODE', 'Code / Programming'), ('VIDEO', 'AI Voice/Video Interview')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewround',
            name='question_format',
            field=models.CharField(choices=[('AUTO', 'AI Recommended'), ('TEXT', 'Text / Typing Answer'), ('MCQ', 'Multiple Choice (Single Answer)'), ('MULTI_SELECT', 'Multiple Choice (Multiple Answers)'), ('CODE', 'Code / Programming'), ('VIDEO', 'AI Voice/Video Interview')], default='TEXT', max_length=20),
        ),
    ]
