# Generated by Django 5.2 on 2026-05-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0016_alter_interviewquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EVALUATING', 'Evaluating'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
