# Generated by Django 5.2 on 2026-06-03 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIrounds', '0017_alter_interviewsession_status'),
        ('jobs', '0015_jobpost_hr_profile_jobpost_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_candidate', to='jobs.jobapplication')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_candidate', to='AIrounds.interviewsession')),
            ],
        ),
    ]
