# Generated by Django 5.2 on 2026-04-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_is_deleted_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('CONNECTION_REQUEST', 'Connection Request'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
