# Generated by Django 5.2 on 2026-04-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('CONNECTION_REQUEST', 'Connection Request'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
