# Generated by Django 5.2 on 2026-05-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_status_notification_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('CONNECTION_REQUEST', 'Connection Request'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('SYSTEM', 'System'), ('INTERVIEW_INVITE', 'Interview Invitation')], max_length=20),
        ),
    ]
