# Generated by Django 5.2 on 2026-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dashboard',
            field=models.CharField(choices=[('USER', 'User Dashboard'), ('RECRUITER', 'Recruiter Dashboard'), ('INTERVIEW', 'Interview Pipeline'), ('HR', 'HR Tool')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('CONNECTION_REQUEST', 'Connection Request'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('SYSTEM', 'System'), ('INTERVIEW_INVITE', 'Interview Invitation'), ('NEW_APPLICATION', 'New Job Application'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('LEAVE_REQUEST', 'Leave Request'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected')], max_length=20),
        ),
    ]
