# Generated by Django 5.2 on 2026-05-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('CONNECTION_REQUEST', 'Connection Request'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('SYSTEM', 'System'), ('INTERVIEW_INVITE', 'Interview Invitation'), ('NEW_APPLICATION', 'New Job Application'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('LEAVE_REQUEST', 'Leave Request'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('NEW_MESSAGE', 'New Message')], max_length=20),
        ),
    ]
