# Generated by Django 5.2 on 2026-05-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='grace_period',
            field=models.IntegerField(default=15, help_text='Grace period in minutes'),
        ),
        migrations.AddField(
            model_name='shift',
            name='min_hours_full_day',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='shift',
            name='min_hours_half_day',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=4),
        ),
    ]
