# Generated by Django 5.2 on 2026-05-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_shift_grace_period_shift_min_hours_full_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
