# Generated by Django 5.2 on 2026-05-19 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_overtime_hours'),
        ('organization', '0004_organization_banner_url_organization_company_size_and_more'),
        ('startups', '0009_companyhrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='startups.startup'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='startups.startup'),
        ),
    ]
