# Generated by Django 5.2 on 2026-08-15 16:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0011_companyprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFollow',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('company', models.ForeignKey(help_text='The company being followed', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='startups.companyprofile')),
                ('follower', models.ForeignKey(help_text='The user who follows the company', on_delete=django.db.models.deletion.CASCADE, related_name='company_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Follow',
                'verbose_name_plural': 'Company Follows',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('follower', models.ForeignKey(help_text='The user who follows', on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(help_text='The user being followed', on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
